# Generated by Django 5.2.6 on 2025-10-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_donador', models.CharField(choices=[('empresa', 'Empresa'), ('restaurant', 'Restaurante'), ('productor', 'Productor Agrícola'), ('persona', 'Persona Natural'), ('otro', 'Otro')], max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donador',
                'verbose_name_plural': 'Donadores',
                'db_table': 'donador',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=100)),
                ('tipo_organizacion', models.CharField(choices=[('junta_vecinos', 'Junta de Vecinos'), ('distribuidora', 'Distribuidora'), ('recolectora', 'Recolectora'), ('otra', 'Otra')], max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'organizacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_usuario', models.CharField(choices=[('donador', 'Donador'), ('organizacion', 'Organización')], default='donador', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_donacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('litros', 'Litros'), ('unidades', 'Unidades'), ('paquetes', 'Paquetes'), ('cajas', 'Cajas')], default='kg', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='appFoodtrack.donador')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donacion',
                'ordering': ['-fecha_donacion'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsable_name', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='appFoodtrack.donacion')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='appFoodtrack.organizacion')),
            ],
            options={
                'verbose_name': 'Recepción de Donación',
                'verbose_name_plural': 'Recepciones de Donaciones',
                'db_table': 'recepciondonacion',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('estado_entrega', models.CharField(choices=[('recogida', 'Recogida'), ('en_transito', 'En Tránsito'), ('entregada_destino', 'Entregada en Destino'), ('rechazada', 'Rechazada'), ('extraviada', 'Extraviada')], max_length=30)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='appFoodtrack.donacion')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='appFoodtrack.organizacion')),
                ('usuario_actualizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_actualizados', to='appFoodtrack.usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de Entrega',
                'verbose_name_plural': 'Seguimientos de Entrega',
                'db_table': 'seguimientoentrega',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
        migrations.AddField(
            model_name='organizacion',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='organizacion_profile', to='appFoodtrack.usuario'),
        ),
        migrations.CreateModel(
            name='HistorialTransacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('crear_donacion', 'Crear Donación'), ('actualizar_donacion', 'Actualizar Donación'), ('recepcionar_donacion', 'Recepción de Donación'), ('actualizar_seguimiento', 'Actualizar Seguimiento'), ('entregar_donacion', 'Entregar Donación'), ('cancelar_donacion', 'Cancelar Donación'), ('login', 'Login'), ('logout', 'Logout'), ('crear_usuario', 'Crear Usuario')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('detalles_json', models.JSONField(blank=True, default=dict)),
                ('donacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='appFoodtrack.donacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='appFoodtrack.usuario')),
            ],
            options={
                'verbose_name': 'Historial de Transacción',
                'verbose_name_plural': 'Historial de Transacciones',
                'db_table': 'historialtransacciones',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.AddField(
            model_name='donador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='donador_profile', to='appFoodtrack.usuario'),
        ),
        migrations.AddIndex(
            model_name='donacion',
            index=models.Index(fields=['estado'], name='donacion_estado_77e5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='donacion',
            index=models.Index(fields=['fecha_donacion'], name='donacion_fecha_d_0adc38_idx'),
        ),
        migrations.AddIndex(
            model_name='donacion',
            index=models.Index(fields=['donador'], name='donacion_donador_b31cc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recepciondonacion',
            unique_together={('donacion', 'organizacion')},
        ),
        migrations.AddIndex(
            model_name='seguimientoentrega',
            index=models.Index(fields=['donacion', 'fecha_seguimiento'], name='seguimiento_donacio_f726b0_idx'),
        ),
        migrations.AddIndex(
            model_name='historialtransacciones',
            index=models.Index(fields=['fecha_accion'], name='historialtr_fecha_a_ed91b5_idx'),
        ),
        migrations.AddIndex(
            model_name='historialtransacciones',
            index=models.Index(fields=['usuario'], name='historialtr_usuario_ad3b22_idx'),
        ),
    ]
