# Generated by Django 5.2.6 on 2025-11-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFoodtrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donador',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
